### ISSUE TITLE
Step by step guide to making a basic script in Doc

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-www#22]
A step by step noob friendly guide on how to make a handler/script for NucleusCoop.

Perhaps it could be for an already released handler, just a step by step process on how to find the right mutex to kill, process name, split gamepads, different focus functions, and the play() function, etc...

It doesn't need to go much in depth, just showing the process of making a simple script from start to finish is plenty enough.

It could be either a video guide, or a written guide.

The guide can be written in markdown, and placed here: https://github.com/SplitScreen-Me/splitscreenme-www/blob/master/docs/create-handlers.md

**Comment by Snailedlt** [comment]
Pizzo from the discord channel has made a good guide on how to start scripting. This can be uploaded and edited to markdown format.

You can download the zip file for the guide [here](https://cdn.discordapp.com/attachments/351721111647551488/810510048694108210/Scripting.zip), once downloaded, unzip it and open `OPEN-ME.html` in the web browser.

**Comment by Snailedlt** [comment]
@Lord-Baldwin-of-Kerry, is this something you would want to do?

**Comment by Lord-Baldwin-of-Kerry** [comment]
@Snailedlt  Sure, will get to that right now!

**Comment by Snailedlt** [comment]
Fixed in pull request -> #38
